### ISSUE TITLE
Подключение чайника 

### ISSUE THREAD

**Issue by stalkerj** [Andrey-m/homebridge-redmond-sh#1]
Добрый день. У меня есть чайник s200, работает из приложения редмонда через блютус. Homebridge соответственно на малине установлен. Ваш плагин позволит управлять чайником доя его включения и выключения или он не все устройства поддерживает?

**Comment by Andrey-m** [comment]
Добрый день.
С чайником данной модели скрипт не проверял.
Поэтому точного ответа не дам. Работу можно проверить только опытным путем.
Если не сработает, можете попробовать другой скрипт который проверен на чайнике, но Redmond SkyKettle RK-M171S.

https://github.com/PimenovAlexander/r4s-bluetooth

**Comment by ChrisGSXR** [comment]
Протестил.
Ваши скрипты (auth on off status) работают с обогревателем REDMOND SkyHeat 7001S
С чайником SkyKettle RK-M171S работает скрипт connect https://github.com/PimenovAlexander/r4s-bluetooth

Скрипт connect корректно забирает текущий режим мощности обогревателя: 
`pi@raspberrypi:~ $ /home/pi/.homebridge/Rdm/4/connect.sh F3:05:6F:93:EF:B7 queryone
Will Control: F3:05:6F:93:EF:B7
Reading primary info
Reading characteristics info
Reading characteristics desc
Attempt to write something -> 0x000c
Attempt to write something -> 0x000c
Characteristic value was written successfully
Attempt to write something -> 0x000e (5500ffb54c75b1b40c88efaa)
REPLY:55 00 ff 01 aa<01>
Authorized
Ok
Characteristic value was written successfully
ON 0C Will keep: 25C REPLY:55 00 06 00 00 19 00 00 00 00 00 02 00 00 00 00 00 00 00 aa
`
Но установить режим работы не выходит =)
